# -*- coding: utf-8 -*-
"""check_alnum.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1atzaNf2t6Zht_5LH6bsp4gwyVXXqJFQH

**7. Check if the word is made up of English letters and is not alpha-numeric**
"""

def check_alnum(word):
  if (word.isalnum())==True:
    st = word + " is alphanumeric"
  else:
    st = word + " is NOT alphanumeric"
  print(st)

check_alnum("abc123")

check_alnum("abc!!")
