# -*- coding: utf-8 -*-
"""conv_lowercase.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/10EUoipQZ1zJBRgIvEp6njK5kCmCun6UN

**9. Convert the word to lowercase**
"""

def lowercase(word):
  print(word.lower())

lowercase("ABCDE")
